import { Keypair, PublicKey } from '@solana/web3.js';
import { BagsSDK } from '../../client';
import { deriveBagsFeeShareV2PartnerConfigPda } from '../fee-share-v2/partner-config';
import { DecodedPartnerConfig } from '../../types/fee-share-v2';
import { signAndSendTransaction } from './transaction';

/**
 * Result of creating a partner key
 */
export interface CreatePartnerKeyResult {
	/** The partner config PDA */
	partnerConfigPda: PublicKey;
	/** The transaction signature (null if already existed) */
	signature: string | null;
	/** The partner config data */
	partnerConfig: DecodedPartnerConfig;
}

/**
 * Result of claiming partner fees
 */
export interface ClaimPartnerFeesResult {
	/** Transaction signatures for each claim transaction */
	signatures: string[];
}

/**
 * Creates a partner key (partner config) for fee sharing.
 *
 * Partner keys allow you to receive a share of fees from token launches that
 * include your partner configuration. By default, partner keys receive 25%
 * (2,500 bps) of the fees generated by tokens launched via that partner key.
 *
 * Each wallet can only have one partner key. If the partner config already
 * exists, this function returns the existing config without creating a new one.
 *
 * @param sdk - The initialized BagsSDK instance
 * @param keypair - The keypair to sign the transaction (must match partnerWallet)
 * @param partnerWallet - Optional wallet address for the partner (defaults to keypair.publicKey)
 * @returns The partner config PDA and creation result
 *
 * @example
 * ```typescript
 * // Create a partner key for your wallet
 * const result = await createPartnerKey(sdk, keypair);
 * console.log(`Partner Config PDA: ${result.partnerConfigPda.toBase58()}`);
 * console.log(`BPS: ${result.partnerConfig.bps}`);
 *
 * // Use the partnerConfigPda in token launches
 * const launchResult = await launchToken(sdk, keypair, {
 *   ...tokenParams,
 *   partner: keypair.publicKey,
 *   partnerConfig: result.partnerConfigPda,
 * });
 * ```
 */
export async function createPartnerKey(
	sdk: BagsSDK,
	keypair: Keypair,
	partnerWallet?: PublicKey
): Promise<CreatePartnerKeyResult> {
	const connection = sdk.state.getConnection();
	const commitment = sdk.state.getCommitment();

	const wallet = partnerWallet ?? keypair.publicKey;
	const partnerConfigPda = deriveBagsFeeShareV2PartnerConfigPda(wallet);

	try {
		const existingConfig = await sdk.partner.getPartnerConfig(wallet);

		return {
			partnerConfigPda,
			signature: null,
			partnerConfig: existingConfig,
		};
	} catch (error: unknown) {
		const errorMessage = error instanceof Error ? error.message : String(error);
		if (!errorMessage.includes('not found')) {
			throw error;
		}
	}

	const { transaction, blockhash } = await sdk.partner.getPartnerConfigCreationTransaction(wallet);

	const signature = await signAndSendTransaction(connection, commitment, transaction, keypair, blockhash);

	const partnerConfig = await sdk.partner.getPartnerConfig(wallet);

	return {
		partnerConfigPda,
		signature,
		partnerConfig,
	};
}

/**
 * Claims all available partner fees for a wallet.
 *
 * Partner fees are accumulated from token launches that include your partner
 * configuration. This function gets and sends all necessary claim transactions.
 *
 * Note: Partners pay transaction fees for all source claim steps. The SOL
 * you're claiming is only received in the final vault-withdraw transaction.
 * Ensure your wallet has sufficient SOL for transaction fees.
 *
 * @param sdk - The initialized BagsSDK instance
 * @param keypair - The keypair to sign transactions (must match partnerWallet)
 * @param partnerWallet - Optional wallet address of the partner (defaults to keypair.publicKey)
 * @returns The claim result with transaction signatures
 *
 * @example
 * ```typescript
 * // Claim partner fees
 * const result = await claimPartnerFees(sdk, keypair);
 * console.log(`Transactions: ${result.signatures.length}`);
 * ```
 */
export async function claimPartnerFees(sdk: BagsSDK, keypair: Keypair): Promise<ClaimPartnerFeesResult> {
	const connection = sdk.state.getConnection();
	const commitment = sdk.state.getCommitment();

	const wallet = keypair.publicKey;

	const claimTransactions = await sdk.partner.getPartnerConfigClaimTransactions(wallet);

	const signatures: string[] = [];

	for (const { transaction, blockhash } of claimTransactions) {
		const signature = await signAndSendTransaction(connection, commitment, transaction, keypair, blockhash);
		signatures.push(signature);
	}

	return { signatures };
}
